services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432"
  
  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static: