services:
  db:
    container_name: postgres16
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./containers/db:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
    networks:
      - coffee_network

  coffee:
    container_name: coffeeapp
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    command: sh -c "/home/appuser/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coffee_network

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: containers/web/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - coffee
    networks:
      - coffee_network

volumes:
  static:
  db_data:

networks:
  coffee_network:
    driver: bridge
