FROM python:3.11-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /home/appuser
ADD requirements.txt /home/appuser/

RUN pip install --upgrade pip && pip install -r requirements.txt
ADD . /home/appuser