FROM python:3.11-bookworm

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_22.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g yarn

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /home/appuser

COPY package.json yarn.lock ./
RUN yarn

ADD requirements.txt /home/appuser/
RUN pip install --upgrade pip && pip install -r requirements.txt

ADD . /home/appuser
